/* Le Mot (facon Wordle) : mots de 5 lettres, sans accent, en MAJUSCULES.
   Sert a la fois de reponses (mot du jour) et de dictionnaire de validation.
   app.js filtre a l'execution pour ne garder que les mots de 5 lettres A-Z. */
window.WORDLE_WORDS = {
  fr: [
    'ARBRE','PORTE','TABLE','LIVRE','CHIEN','ROUGE','VERTE','JAUNE','PLAGE','ROUTE',
    'MONDE','TERRE','FLEUR','POMME','SUCRE','LAPIN','MARIN','VOILE','NUAGE','ORAGE',
    'PLUIE','NEIGE','SABLE','VITRE','RADIO','PIANO','GUIDE','FORCE','SPORT','MATCH',
    'BALLE','POCHE','VESTE','BOTTE','ECOLE','REGLE','STYLO','ELEVE','NOTES','COURS',
    'TEXTE','ROBOT','AVION','TRAIN','HOTEL','VERRE','VILLE','MERCI','SALUT','HEURE',
    'JOURS','TIGRE','LIONS','OURSE','SINGE','VACHE','CHATS','POULE','ZEBRE','LOUPS',
    'PONEY','PORCS','VEAUX','PATES','PAINS','GLACE','FRITE','STEAK','FRUIT','MELON',
    'DATTE','FIGUE','OLIVE','POIRE','PECHE','PRUNE','CREME','OEUFS','LAMPE','TAPIS',
    'DRAPS','TASSE','BOCAL','SEAUX','BALAI','JOUER','GAGNE','PERDU','SCORE','POINT',
    'DEFIS','LIBRE','FORTS','MALIN','SAGES','DROLE','BEAUX','JOLIE','PLATS','ROSES',
    'BLEUE','NOIRE','BLANC','GRISE','MAUVE','OCEAN','RIVES','MERES','PERES','FILLE',
    'AMOUR','COEUR','MAINS','PIEDS','DENTS','LEVRE','PARLE','MOTOS','VELOS','PONTS',
    'GARES','METRO','TROIS','ROULE','SAUTE','COURT','MILLE','DANSE','CHANT','RIRES',
  ],
  en: [
    'APPLE','HOUSE','TABLE','CHAIR','WATER','LIGHT','NIGHT','MONEY','HAPPY','MUSIC',
    'DANCE','SMILE','HEART','BRAIN','POWER','SPACE','EARTH','OCEAN','RIVER','BEACH',
    'CLOUD','STORM','GREEN','WHITE','BLACK','BROWN','PLANT','TREES','GRASS','FRUIT',
    'LEMON','MANGO','BREAD','SUGAR','HONEY','JUICE','PIZZA','SALAD','STEAK','PASTA',
    'CANDY','SWEET','GRAPE','PEACH','BERRY','MELON','TIGER','LIONS','BEARS','HORSE',
    'SHEEP','GOATS','MOUSE','SNAKE','EAGLE','SHARK','WHALE','ZEBRA','PANDA','KOALA',
    'CAMEL','PUPPY','KITTY','FROGS','DUCKS','BIRDS','SCORE','POINT','LEVEL','BOARD',
    'CHESS','CARDS','MATCH','QUEEN','KINGS','ROOKS','PAWNS','PIECE','HELLO','WORLD',
    'SMART','QUICK','BRAVE','FUNNY','LUCKY','MAGIC','DREAM','SLEEP','LEARN','STUDY',
    'BOOKS','WORDS','VOWEL','SOUND','VOICE','PHONE','VIDEO','EMAIL','ROBOT','TRAIN',
    'PLANE','HOTEL','GLASS','PLATE','SPOON','KNIFE','CLOCK','WATCH','SHOES','SHIRT',
    'PANTS','DRESS','SOCKS','TOWEL','BRUSH','RIVER','MOUNT','FIELD','GRAND','SUNNY',
    'RAINY','WINDY','FROST','SPARK','FLAME','STONE','METAL','PAPER','WOODS','CROWN',
  ],
};
