/* Le Mot (facon Wordle) : mots de 5 lettres, sans accent, en MAJUSCULES.
   Sert a la fois de reponses (mot du jour) et de dictionnaire de validation.
   app.js filtre a l'execution pour ne garder que les mots de 5 lettres A-Z. */
window.WORDLE_WORDS = {
  fr: [
    'ARBRE','PORTE','TABLE','LIVRE','CHIEN','ROUGE','VERTE','JAUNE','PLAGE','ROUTE',
    'MONDE','TERRE','FLEUR','POMME','SUCRE','LAPIN','MARIN','VOILE','NUAGE','ORAGE',
    'PLUIE','NEIGE','SABLE','VITRE','RADIO','PIANO','GUIDE','FORCE','SPORT','MATCH',
    'BALLE','POCHE','VESTE','BOTTE','ECOLE','REGLE','STYLO','ELEVE','NOTES','COURS',
    'TEXTE','ROBOT','AVION','TRAIN','HOTEL','VERRE','VILLE','MERCI','SALUT','HEURE',
    'JOURS','TIGRE','LIONS','OURSE','SINGE','VACHE','CHATS','POULE','ZEBRE','LOUPS',
    'PONEY','PORCS','VEAUX','PATES','PAINS','GLACE','FRITE','STEAK','FRUIT','MELON',
    'DATTE','FIGUE','OLIVE','POIRE','PECHE','PRUNE','CREME','OEUFS','LAMPE','TAPIS',
    'DRAPS','TASSE','BOCAL','SEAUX','BALAI','JOUER','GAGNE','PERDU','SCORE','POINT',
    'DEFIS','LIBRE','FORTS','MALIN','SAGES','DROLE','BEAUX','JOLIE','PLATS','ROSES',
    'BLEUE','NOIRE','BLANC','GRISE','MAUVE','OCEAN','RIVES','MERES','PERES','FILLE',
    'AMOUR','COEUR','MAINS','PIEDS','DENTS','LEVRE','PARLE','MOTOS','VELOS','PONTS',
    'GARES','METRO','TROIS','ROULE','SAUTE','COURT','MILLE','DANSE','CHANT','RIRES',
  ],
  en: [
    'APPLE','HOUSE','TABLE','CHAIR','WATER','LIGHT','NIGHT','MONEY','HAPPY','MUSIC',
    'DANCE','SMILE','HEART','BRAIN','POWER','SPACE','EARTH','OCEAN','RIVER','BEACH',
    'CLOUD','STORM','GREEN','WHITE','BLACK','BROWN','PLANT','TREES','GRASS','FRUIT',
    'LEMON','MANGO','BREAD','SUGAR','HONEY','JUICE','PIZZA','SALAD','STEAK','PASTA',
    'CANDY','SWEET','GRAPE','PEACH','BERRY','MELON','TIGER','LIONS','BEARS','HORSE',
    'SHEEP','GOATS','MOUSE','SNAKE','EAGLE','SHARK','WHALE','ZEBRA','PANDA','KOALA',
    'CAMEL','PUPPY','KITTY','FROGS','DUCKS','BIRDS','SCORE','POINT','LEVEL','BOARD',
    'CHESS','CARDS','MATCH','QUEEN','KINGS','ROOKS','PAWNS','PIECE','HELLO','WORLD',
    'SMART','QUICK','BRAVE','FUNNY','LUCKY','MAGIC','DREAM','SLEEP','LEARN','STUDY',
    'BOOKS','WORDS','VOWEL','SOUND','VOICE','PHONE','VIDEO','EMAIL','ROBOT','TRAIN',
    'PLANE','HOTEL','GLASS','PLATE','SPOON','KNIFE','CLOCK','WATCH','SHOES','SHIRT',
    'PANTS','DRESS','SOCKS','TOWEL','BRUSH','RIVER','MOUNT','FIELD','GRAND','SUNNY',
    'RAINY','WINDY','FROST','SPARK','FLAME','STONE','METAL','PAPER','WOODS','CROWN',
  ],
};

/* Indices du mot du jour : une phrase enigmatique par mot, qui ne contient
   jamais la reponse et laisse reflechir. Cle = mot en MAJUSCULES. */
window.WORDLE_HINTS = {
  fr: {
    ARBRE:"Il donne de l'ombre l'ete et perd ses feuilles l'automne.",
    PORTE:"On la pousse ou on la tire pour entrer dans une piece.",
    TABLE:"On y pose les assiettes a l'heure du repas.",
    LIVRE:"Des pages reliees pleines d'histoires a lire.",
    CHIEN:"Le meilleur ami de l'homme, il aboie et remue la queue.",
    ROUGE:"La couleur du sang et des cerises bien mures.",
    VERTE:"La teinte des feuilles au printemps, au feminin.",
    JAUNE:"La couleur du citron et du gros soleil de midi.",
    PLAGE:"Du sable fin, des vagues et des parasols.",
    ROUTE:"Les voitures y roulent d'une ville a l'autre.",
    MONDE:"La planete entiere et tous ceux qui l'habitent.",
    TERRE:"Notre planete bleue, ou le sol sous nos pieds.",
    FLEUR:"Elle sent bon et s'offre en bouquet.",
    POMME:"Un fruit rond qui tenta Blanche-Neige.",
    SUCRE:"Il rend le cafe et les gateaux moins amers.",
    LAPIN:"De grandes oreilles et un faible pour les carottes.",
    MARIN:"Il vit et travaille sur les mers.",
    VOILE:"Le vent la gonfle pour faire avancer le bateau.",
    NUAGE:"Il flotte dans le ciel et annonce parfois la pluie.",
    ORAGE:"Eclairs et tonnerre grondent dans le ciel noir.",
    PLUIE:"Elle tombe des nuages et mouille les rues.",
    NEIGE:"Blanche et froide, elle recouvre tout l'hiver.",
    SABLE:"Fin et dore, il file entre les doigts au bord de mer.",
    VITRE:"On voit au travers, elle ferme la fenetre.",
    RADIO:"On l'ecoute pour la musique et les informations.",
    PIANO:"Un instrument a grandes touches noires et blanches.",
    GUIDE:"Il montre le chemin aux visiteurs et raconte l'histoire.",
    FORCE:"La puissance des muscles ou du caractere.",
    SPORT:"Le foot, la course et la natation en font partie.",
    MATCH:"Une rencontre disputee entre deux equipes.",
    BALLE:"Ronde, on la lance, la frappe ou la rattrape.",
    POCHE:"Dans le pantalon, on y range ses cles.",
    VESTE:"On l'enfile par-dessus la chemise quand il fait frais.",
    BOTTE:"Une chaussure haute pour la pluie ou la boue.",
    ECOLE:"On y apprend a lire, a ecrire et a compter.",
    REGLE:"Un instrument droit pour tracer, ou une consigne a suivre.",
    STYLO:"Rempli d'encre, il sert a ecrire.",
    ELEVE:"Il s'assoit en classe et ecoute le maitre.",
    NOTES:"Le professeur les met sur les copies.",
    COURS:"La lecon donnee par le professeur.",
    TEXTE:"Un ensemble de mots ecrits, a lire.",
    ROBOT:"Une machine qui obeit et bouge toute seule.",
    AVION:"Il vole haut dans le ciel grace a ses ailes.",
    TRAIN:"Il roule sur des rails avec une file de wagons.",
    HOTEL:"On y dort en voyage, il y a une reception.",
    VERRE:"On y boit de l'eau, il peut se briser.",
    VILLE:"Beaucoup de maisons, de rues et d'habitants.",
    MERCI:"Ce qu'on dit poliment quand on recoit un cadeau.",
    SALUT:"Un petit bonjour amical entre copains.",
    HEURE:"Soixante minutes qui s'ecoulent.",
    JOURS:"Lundi, mardi et mercredi en sont, au pluriel.",
    TIGRE:"Un grand felin raye, orange et noir.",
    LIONS:"Les rois de la savane, au pluriel.",
    OURSE:"La femelle qui hiverne avec ses petits.",
    SINGE:"Il grimpe aux arbres et imite tout.",
    VACHE:"Elle rumine dans le pre et donne du lait.",
    CHATS:"Ils ronronnent et chassent les souris, au pluriel.",
    POULE:"Elle pond des oeufs et glousse dans la basse-cour.",
    ZEBRE:"Un cheval sauvage a rayures d'Afrique.",
    LOUPS:"En meute, ils hurlent a la lune, au pluriel.",
    PONEY:"Un tout petit cheval que montent les enfants.",
    PORCS:"Roses et grognons, ils aiment la boue, au pluriel.",
    VEAUX:"Les petits de la vache, au pluriel.",
    PATES:"Spaghettis et macaronis en font partie.",
    PAINS:"On les achete chauds chez le boulanger, au pluriel.",
    GLACE:"Froide et sucree, elle fond au soleil.",
    FRITE:"Une lamelle de pomme de terre doree dans l'huile.",
    STEAK:"Une belle tranche de viande grillee.",
    FRUIT:"La banane, l'orange ou la cerise en sont un.",
    MELON:"Un gros rond, vert dehors et orange dedans.",
    DATTE:"Le fruit tres sucre du palmier.",
    FIGUE:"Un fruit violet plein de minuscules graines.",
    OLIVE:"Petite, verte ou noire, on en tire de l'huile.",
    POIRE:"Un fruit en forme de goutte.",
    PECHE:"Un fruit velu a noyau, ou l'art de prendre du poisson.",
    PRUNE:"Un petit fruit violet a noyau.",
    CREME:"Onctueuse, on l'etale sur les gateaux.",
    OEUFS:"La poule les pond, au pluriel.",
    LAMPE:"Elle eclaire la piece quand on l'allume.",
    TAPIS:"On marche dessus, il couvre le sol.",
    DRAPS:"On les met sur le lit pour dormir, au pluriel.",
    TASSE:"On y boit le the ou le cafe, avec une anse.",
    BOCAL:"Un pot en verre pour les confitures.",
    SEAUX:"On y met de l'eau, ideal pour le chateau de sable.",
    BALAI:"On s'en sert pour ramasser la poussiere.",
    JOUER:"L'action de s'amuser a un jeu.",
    GAGNE:"Ce qu'a fait celui qui a remporte la partie.",
    PERDU:"Le contraire d'avoir gagne.",
    SCORE:"Le nombre de points obtenus dans une partie.",
    POINT:"L'unite qu'on marque pour progresser.",
    DEFIS:"Des epreuves a relever chaque jour, au pluriel.",
    LIBRE:"Sans chaine ni prison, qui va ou il veut.",
    FORTS:"Pleins de muscles et de puissance, au pluriel.",
    MALIN:"Ruse et debrouillard.",
    SAGES:"Bien calmes et raisonnables, au pluriel.",
    DROLE:"Il fait rire tout le monde.",
    BEAUX:"Tres agreables a regarder, au pluriel.",
    JOLIE:"Charmante a regarder, au feminin.",
    PLATS:"Les mets qu'on sert a table, au pluriel.",
    ROSES:"Des fleurs a epines qu'on offre par amour.",
    BLEUE:"La couleur du ciel degage, au feminin.",
    NOIRE:"La couleur de la nuit sans lune, au feminin.",
    BLANC:"La couleur de la neige et du lait.",
    GRISE:"Entre le noir et le blanc, au feminin.",
    MAUVE:"Un violet pale et tres doux.",
    OCEAN:"Une immense etendue d'eau salee.",
    RIVES:"Les bords d'un fleuve, au pluriel.",
    MERES:"Les mamans, au pluriel.",
    PERES:"Les papas, au pluriel.",
    FILLE:"Une jeune enfant de sexe feminin.",
    AMOUR:"Le sentiment qui fait battre le coeur.",
    COEUR:"L'organe qui bat dans la poitrine.",
    MAINS:"Au bout des bras, avec cinq doigts chacune.",
    PIEDS:"Au bout des jambes, ils portent les chaussures.",
    DENTS:"Blanches dans la bouche, pour croquer.",
    LEVRE:"On s'en sert pour embrasser ou prononcer les mots.",
    PARLE:"Ce que fait celui qui prononce des mots a voix haute.",
    MOTOS:"Deux roues a moteur qui petaradent, au pluriel.",
    VELOS:"Deux roues a pedales, au pluriel.",
    PONTS:"Ils enjambent les rivieres, au pluriel.",
    GARES:"On y prend le train, au pluriel.",
    METRO:"Un train souterrain des grandes villes.",
    TROIS:"Le chiffre entre deux et quatre.",
    ROULE:"Ce que fait la voiture qui avance.",
    SAUTE:"Ce que fait celui qui bondit en l'air.",
    COURT:"Le contraire de long, ou celui qui va tres vite.",
    MILLE:"Dix fois cent.",
    DANSE:"On la fait en bougeant sur la musique.",
    CHANT:"Une melodie faite avec la voix.",
    RIRES:"Ce qui eclate quand c'est vraiment drole, au pluriel.",
  },
  en: {
    APPLE:"A round fruit said to keep the doctor away.",
    HOUSE:"A place with walls and a roof where a family lives.",
    TABLE:"You set the plates on it to eat.",
    CHAIR:"You sit on it at your desk.",
    WATER:"It flows in rivers and you drink it every day.",
    LIGHT:"It shines and chases away the dark.",
    NIGHT:"The dark hours when the stars appear.",
    MONEY:"You use it to buy things at the shop.",
    HAPPY:"How you feel when everything goes well.",
    MUSIC:"Melody and rhythm you listen to.",
    DANCE:"Moving your body to the beat.",
    SMILE:"What your lips do when you are glad.",
    HEART:"It beats inside your chest.",
    BRAIN:"The organ inside your head that thinks.",
    POWER:"Great strength or energy.",
    SPACE:"Where the stars and planets float.",
    EARTH:"The blue planet we all live on.",
    OCEAN:"A vast body of salt water.",
    RIVER:"Flowing water running between two banks.",
    BEACH:"Sand and waves right by the sea.",
    CLOUD:"It floats in the sky and may bring rain.",
    STORM:"Thunder and lightning striking together.",
    GREEN:"The color of grass and fresh leaves.",
    WHITE:"The color of fresh snow and milk.",
    BLACK:"The color of a moonless night.",
    BROWN:"The color of chocolate and tree bark.",
    PLANT:"It grows from the soil with roots and leaves.",
    TREES:"Tall wooden growers with leaves, plural.",
    GRASS:"The green carpet of a lawn.",
    FRUIT:"An apple or a banana is one of these.",
    LEMON:"A sour yellow citrus.",
    MANGO:"A sweet tropical fruit with a big pit.",
    BREAD:"The baker makes it from flour every morning.",
    SUGAR:"It makes your coffee taste sweet.",
    HONEY:"The sweet golden syrup made by bees.",
    JUICE:"The liquid squeezed out of a fruit.",
    PIZZA:"A round Italian dish topped with cheese.",
    SALAD:"A bowl of fresh raw vegetables.",
    STEAK:"A thick slice of grilled meat.",
    PASTA:"Spaghetti and macaroni are this.",
    CANDY:"A sweet treat that kids adore.",
    SWEET:"The taste of sugar and honey.",
    GRAPE:"A small round fruit growing in bunches.",
    PEACH:"A soft fuzzy fruit with a pit.",
    BERRY:"A tiny juicy fruit that grows on bushes.",
    MELON:"A big round fruit, sweet and juicy inside.",
    TIGER:"A striped big cat, orange and black.",
    LIONS:"The kings of the savanna, plural.",
    BEARS:"Big furry animals that hibernate, plural.",
    HORSE:"You ride it and it neighs.",
    SHEEP:"A woolly farm animal that says baa.",
    GOATS:"They climb rocks and nibble almost anything, plural.",
    MOUSE:"A tiny animal a cat chases, or moves a cursor.",
    SNAKE:"A long legless reptile that slithers.",
    EAGLE:"A great bird of prey with piercing eyes.",
    SHARK:"A fearsome fish with rows of teeth.",
    WHALE:"The biggest animal in the sea.",
    ZEBRA:"A striped wild horse of Africa.",
    PANDA:"A black and white bear that eats bamboo.",
    KOALA:"A furry animal that hugs eucalyptus branches.",
    CAMEL:"A desert animal with one or two humps.",
    PUPPY:"A very young dog.",
    KITTY:"A cute little cat.",
    FROGS:"Green jumpers that croak, plural.",
    DUCKS:"Birds that swim and quack, plural.",
    BIRDS:"Feathered animals that fly and sing, plural.",
    SCORE:"The number of points you earn.",
    POINT:"One unit you win in a game.",
    LEVEL:"A stage you reach as you get better.",
    BOARD:"You play chess or checkers on it.",
    CHESS:"A game of kings, queens and pawns.",
    CARDS:"You deal them out to play games, plural.",
    MATCH:"A contest between two teams.",
    QUEEN:"The most powerful piece on the chessboard.",
    KINGS:"Crowned rulers of a realm, plural.",
    ROOKS:"The castle-shaped chess pieces, plural.",
    PAWNS:"The smallest chess soldiers, plural.",
    PIECE:"One part of a whole, or a chessman.",
    HELLO:"The word you say to greet someone.",
    WORLD:"The whole planet and everyone on it.",
    SMART:"Clever and quick to learn.",
    QUICK:"Very fast, done in no time.",
    BRAVE:"Full of courage and not afraid.",
    FUNNY:"It makes everyone laugh out loud.",
    LUCKY:"Blessed with good fortune.",
    MAGIC:"Wizards and spells belong to it.",
    DREAM:"A story your mind tells while you sleep.",
    SLEEP:"What you do at night in your bed.",
    LEARN:"To gain new knowledge.",
    STUDY:"What you do hard before an exam.",
    BOOKS:"Bound pages full of stories, plural.",
    WORDS:"Letters put together to carry meaning, plural.",
    VOWEL:"A, E, I, O or U is one of these.",
    SOUND:"What your ears pick up.",
    VOICE:"The sound you make when you speak.",
    PHONE:"You call and text with it.",
    VIDEO:"A moving picture you watch on a screen.",
    EMAIL:"A letter sent over the internet.",
    ROBOT:"A machine that moves on its own.",
    TRAIN:"It runs on rails pulling many cars.",
    PLANE:"It flies high on two wings.",
    HOTEL:"You sleep there while traveling.",
    GLASS:"You drink water from it, and it can break.",
    PLATE:"You put your food on it at dinner.",
    SPOON:"You eat your soup with it.",
    KNIFE:"A sharp tool to cut your food.",
    CLOCK:"It hangs on the wall and shows the time.",
    WATCH:"A tiny clock you wear on your wrist.",
    SHOES:"You wear them on your feet, plural.",
    SHIRT:"You wear it on your upper body.",
    PANTS:"You wear them on your legs, plural.",
    DRESS:"A one-piece outfit girls often wear.",
    SOCKS:"You slip them on under your shoes, plural.",
    TOWEL:"You dry yourself with it after a shower.",
    BRUSH:"You use it on your hair or your teeth.",
    MOUNT:"A very high peak, short and grand.",
    FIELD:"An open stretch of land or a football ground.",
    GRAND:"Large, noble and impressive.",
    SUNNY:"A bright day full of warm sunshine.",
    RAINY:"A wet day full of showers.",
    WINDY:"A day when the air blows hard.",
    FROST:"The thin white ice on cold mornings.",
    SPARK:"A tiny flash of fire.",
    FLAME:"The dancing tongue of a fire.",
    STONE:"A hard little piece of rock.",
    METAL:"Iron, gold and silver are this.",
    PAPER:"You write on it, and it is made from wood.",
    WOODS:"A small forest full of trees, plural.",
    CROWN:"The king wears it on his head.",
  },
};
