/* Le Mot (facon Wordle) : mots de 5 lettres, sans accent, en MAJUSCULES.
   Sert a la fois de reponses (mot du jour) et de dictionnaire de validation.
   app.js filtre a l'execution pour ne garder que les mots de 5 lettres A-Z. */
window.WORDLE_WORDS = {
  fr: [
    'ARBRE','PORTE','TABLE','LIVRE','CHIEN','ROUGE','VERTE','JAUNE','PLAGE','ROUTE',
    'MONDE','TERRE','FLEUR','POMME','SUCRE','LAPIN','MARIN','VOILE','NUAGE','ORAGE',
    'PLUIE','NEIGE','SABLE','VITRE','RADIO','PIANO','GUIDE','FORCE','SPORT','MATCH',
    'BALLE','POCHE','VESTE','BOTTE','ECOLE','REGLE','STYLO','ELEVE','NOTES','COURS',
    'TEXTE','ROBOT','AVION','TRAIN','HOTEL','VERRE','VILLE','MERCI','SALUT','HEURE',
    'JOURS','TIGRE','LIONS','OURSE','SINGE','VACHE','CHATS','POULE','ZEBRE','LOUPS',
    'PONEY','PORCS','VEAUX','PATES','PAINS','GLACE','FRITE','STEAK','FRUIT','MELON',
    'DATTE','FIGUE','OLIVE','POIRE','PECHE','PRUNE','CREME','OEUFS','LAMPE','TAPIS',
    'DRAPS','TASSE','BOCAL','SEAUX','BALAI','JOUER','GAGNE','PERDU','SCORE','POINT',
    'DEFIS','LIBRE','FORTS','MALIN','SAGES','DROLE','BEAUX','JOLIE','PLATS','ROSES',
    'BLEUE','NOIRE','BLANC','GRISE','MAUVE','OCEAN','RIVES','MERES','PERES','FILLE',
    'AMOUR','COEUR','MAINS','PIEDS','DENTS','LEVRE','PARLE','MOTOS','VELOS','PONTS',
    'GARES','METRO','TROIS','ROULE','SAUTE','COURT','MILLE','DANSE','CHANT','RIRES',
  ],
  en: [
    'APPLE','HOUSE','TABLE','CHAIR','WATER','LIGHT','NIGHT','MONEY','HAPPY','MUSIC',
    'DANCE','SMILE','HEART','BRAIN','POWER','SPACE','EARTH','OCEAN','RIVER','BEACH',
    'CLOUD','STORM','GREEN','WHITE','BLACK','BROWN','PLANT','TREES','GRASS','FRUIT',
    'LEMON','MANGO','BREAD','SUGAR','HONEY','JUICE','PIZZA','SALAD','STEAK','PASTA',
    'CANDY','SWEET','GRAPE','PEACH','BERRY','MELON','TIGER','LIONS','BEARS','HORSE',
    'SHEEP','GOATS','MOUSE','SNAKE','EAGLE','SHARK','WHALE','ZEBRA','PANDA','KOALA',
    'CAMEL','PUPPY','KITTY','FROGS','DUCKS','BIRDS','SCORE','POINT','LEVEL','BOARD',
    'CHESS','CARDS','MATCH','QUEEN','KINGS','ROOKS','PAWNS','PIECE','HELLO','WORLD',
    'SMART','QUICK','BRAVE','FUNNY','LUCKY','MAGIC','DREAM','SLEEP','LEARN','STUDY',
    'BOOKS','WORDS','VOWEL','SOUND','VOICE','PHONE','VIDEO','EMAIL','ROBOT','TRAIN',
    'PLANE','HOTEL','GLASS','PLATE','SPOON','KNIFE','CLOCK','WATCH','SHOES','SHIRT',
    'PANTS','DRESS','SOCKS','TOWEL','BRUSH','RIVER','MOUNT','FIELD','GRAND','SUNNY',
    'RAINY','WINDY','FROST','SPARK','FLAME','STONE','METAL','PAPER','WOODS','CROWN',
  ],
};

/* Indices du mot du jour : une enigme par mot, volontairement retorse
   (metaphores, doubles sens, detours), qui ne contient JAMAIS la reponse.
   Cle = mot en MAJUSCULES. */
window.WORDLE_HINTS = {
  fr: {
    ARBRE:"Immobile geant, je respire par mes bras et l'automne me deshabille.",
    PORTE:"Gardienne muette, je separe le dedans du dehors et tourne sur un gond.",
    TABLE:"A quatre pattes sans jamais courir, je porte vos festins.",
    LIVRE:"Muet, je parle a qui m'ouvre ; mille voix dorment entre mes feuilles.",
    CHIEN:"Fidele ombre de l'homme, je garde et fais du bruit sans dire un mot.",
    ROUGE:"Couleur de la colere, du feu et de ce qui coule dans tes veines.",
    VERTE:"Immature ou printaniere, au feminin je porte l'espoir.",
    JAUNE:"Traitre dit-on, pourtant c'est la teinte du soleil et de l'or pale.",
    PLAGE:"La ou la terre se rend a la mer, grain a grain.",
    ROUTE:"Ruban de bitume qui relie les cites et ne dort jamais.",
    MONDE:"Tout ce qui existe tient dans ce petit globe.",
    TERRE:"Sous tes pas ou perdue dans le vide, elle est bleue vue de loin.",
    FLEUR:"Ephemere beaute qui se fane ; on la cueille pour dire je t'aime.",
    POMME:"Newton lui doit une idee, Eve une tentation.",
    SUCRE:"Blanc cristal qui adoucit sans jamais saler.",
    LAPIN:"On me pose a qui rate un rendez-vous ; sinon je creuse et je detale.",
    MARIN:"L'horizon est mon quotidien et le sel ma compagnie.",
    VOILE:"Toile tendue qui derobe le vent pour avancer.",
    NUAGE:"Vagabond du ciel, je pleure parfois sur vos parapluies.",
    ORAGE:"Colere du ciel : d'abord l'eclair, puis le grondement.",
    PLUIE:"Le ciel se vide et les escargots sortent.",
    NEIGE:"Silence blanc qui tombe et efface les couleurs.",
    SABLE:"Le temps s'ecoule a travers moi, enferme dans un verre.",
    VITRE:"Frontiere transparente : je laisse voir mais pas passer.",
    RADIO:"Sans image, je remplis le silence de voix et de chansons.",
    PIANO:"Alternance de deuil et de lumiere, je chante sous les doigts.",
    GUIDE:"Je connais le chemin que les autres ignorent.",
    FORCE:"Ce qui souleve la fonte ou deplace les montagnes.",
    SPORT:"La sueur y est vertu et la coupe un trophee.",
    MATCH:"Deux camps, un arbitre, un enjeu : rendez-vous compte.",
    BALLE:"Ronde et bondissante, ou petite et mortelle dans un canon.",
    POCHE:"Trou cousu ou dorment cles et secrets.",
    VESTE:"On me ramasse quand on echoue en politique ; sinon je tiens chaud aux epaules.",
    BOTTE:"Haute chaussure du cavalier, ou coup secret de l'escrimeur.",
    ECOLE:"On y entre ignorant, on en ressort un peu moins.",
    REGLE:"Droite je mesure, ecrite je m'impose a tous.",
    STYLO:"Je saigne de l'encre pour laisser une trace.",
    ELEVE:"Assis pour apprendre, ou participe passe de grandir.",
    NOTES:"Chiffres qui jugent la copie, ou sons qui font la musique.",
    COURS:"Lecon du maitre, lit de la riviere, ou ordre de filer vite.",
    TEXTE:"Suite de signes ou sommeille un sens.",
    ROBOT:"Serviteur de metal, sans ame ni fatigue.",
    AVION:"Trop lourd pour la nature, il vole pourtant d'un continent a l'autre.",
    TRAIN:"Serpent d'acier qui suit deux lignes sans jamais s'en ecarter.",
    HOTEL:"Chez soi loin de chez soi, avec une cle a rendre.",
    VERRE:"Fragile et transparent, il contient l'eau et trinque a la fete.",
    VILLE:"Fourmiliere humaine de pierre et de bitume.",
    MERCI:"Petit mot de gratitude, ou etre a l'entiere disposition d'autrui.",
    SALUT:"Bonjour familier, ou le fait d'echapper au pire.",
    HEURE:"Soixante minutes reunies ; l'aiguille me designe.",
    JOURS:"Ils se suivent en semaine et ne se ressemblent pas.",
    TIGRE:"Seigneur raye de la jungle, de feu et d'ombre.",
    LIONS:"Couronnes de criniere, ils regnent sans trone.",
    OURSE:"La Grande brille au ciel etoile ; sur terre elle veille sur ses petits.",
    SINGE:"Cousin moqueur qui copie tout ce qu'il voit.",
    VACHE:"Elle donne le blanc du matin en ruminant sans fin.",
    CHATS:"Neuf vies dit-on, des griffes retractiles et un ronron.",
    POULE:"Elle precede ou suit l'oeuf, nul ne sait vraiment.",
    ZEBRE:"Cheval en pyjama raye des savanes.",
    LOUPS:"En bande ils chantent a la lune ; les contes les font craindre.",
    PONEY:"Cheval en miniature, monture des enfants.",
    PORCS:"Roses et boueux, dit-on que rien ne se perd d'eux.",
    VEAUX:"Ils tetent celle qui donne le blanc du matin.",
    PATES:"Nees d'eau et de ble, on les noie sous la sauce.",
    PAINS:"Quand on en a sur la planche, on croule sous le travail.",
    GLACE:"Froide je fonds au soleil, verticale je te renvoie ton reflet.",
    FRITE:"Doree dans l'huile ; on l'a bonne quand tout va bien.",
    STEAK:"L'ogre le prefere rouge et saignant.",
    FRUIT:"Ce que porte l'arbre, et ce que recolte l'effort.",
    MELON:"Rond a rayures, sucre l'ete ; ou chapeau des dandys anglais.",
    DATTE:"Sucre du desert, joyau suspendu au palmier.",
    FIGUE:"Fendue elle revele mille grains ; partagee moitie-moitie avec le raisin.",
    OLIVE:"Amere sur l'arbre, huile dans l'assiette, rameau de paix.",
    POIRE:"En forme de larme ; naif, on te prend pour elle.",
    PECHE:"Duvet sur la peau, gros noyau au coeur, cousine de l'abricot.",
    PRUNE:"Petite violette a noyau, cousine de la mirabelle.",
    CREME:"Le meilleur de tous ; onctueuse, elle couronne le gateau.",
    OEUFS:"Fragiles coques d'ou sortiront des poussins.",
    LAMPE:"Genie dedans ou ampoule dessus, je chasse l'obscurite.",
    TAPIS:"Volant dans les contes, il dort sous vos pieds.",
    DRAPS:"Blancs voiles du sommeil ou l'on se glisse le soir.",
    TASSE:"Petit recipient a anse pour un breuvage bien chaud.",
    BOCAL:"Prison de verre du poisson rouge, ou refuge des confitures.",
    SEAUX:"Ils portent l'eau deux par deux, rois du chateau de sable.",
    BALAI:"Monture de sorciere qui pourchasse la poussiere.",
    JOUER:"Ce que font l'enfant, le comedien et le musicien.",
    GAGNE:"Le sourire du premier au tableau des scores.",
    PERDU:"Sans repere, sans victoire, sans retour.",
    SCORE:"Compte des exploits affiche a la fin de la partie.",
    POINT:"Minuscule sur le i, decisif dans le jeu.",
    DEFIS:"Gants jetes qu'il faut ramasser.",
    LIBRE:"Ni cage, ni chaine, ni maitre.",
    FORTS:"Chateaux de sable, ou muscles au pluriel.",
    MALIN:"Le renard l'est ; le diable en personne aussi.",
    SAGES:"Trois vinrent d'Orient ; ils ne font jamais de betises.",
    DROLE:"Etrange parfois, hilarant souvent.",
    BEAUX:"Ce que sont les gendres pour la belle-mere ; agreables a l'oeil.",
    JOLIE:"Charmante au feminin, sans etre eblouissante.",
    PLATS:"Les services d'un repas, ou l'inverse du relief.",
    ROSES:"A epines, on les offre par amour ; la vie en devient optimiste.",
    BLEUE:"Couleur du ciel sans nuage et de l'ocean profond, au feminin.",
    NOIRE:"Couleur du deuil et du cafe serre, au feminin.",
    BLANC:"Toutes les lumieres melees ; page vierge ou trou de memoire.",
    GRISE:"Melange de nuit et de jour, teinte des ciels maussades, au feminin.",
    MAUVE:"Violet tres pale, couleur d'une petite fleur des champs.",
    OCEAN:"Immensite salee ou plongent les baleines.",
    RIVES:"Bords que le fleuve caresse a droite et a gauche.",
    MERES:"Celles qui ont porte la vie, fetees au mois de mai.",
    PERES:"Fetes en juin, ils forment le couple parental avec la maman.",
    FILLE:"Jeune humaine, ou l'enfant de ses parents au feminin.",
    AMOUR:"Aveugle dit-on, il rend fou et fait ecrire les poetes.",
    COEUR:"Pompe infatigable ; symbole rouge du quatorze fevrier.",
    MAINS:"Cinq doigts chacune, elles applaudissent et travaillent.",
    PIEDS:"Ils foulent le sol et comptent les syllabes d'un vers.",
    DENTS:"Emaux blancs qui broient les aliments dans la bouche.",
    LEVRE:"Frontiere charnue du sourire et du baiser.",
    PARLE:"Ce que fait la bouche qui n'est pas muette.",
    MOTOS:"Deux roues rugissantes chevauchees par les bikers.",
    VELOS:"Deux roues qu'on fait tourner a la force des mollets.",
    PONTS:"Ils enjambent rivieres et vallees pour relier deux bords.",
    GARES:"Quais, horaires et adieux ; le train y fait halte.",
    METRO:"Taupe urbaine du boulot-dodo.",
    TROIS:"Nombre des mousquetaires... qui etaient pourtant quatre.",
    ROULE:"Ce que fait la boule qui devale la pente.",
    SAUTE:"Ce que fait la puce, le cascadeur et l'oeuf dans la poele.",
    COURT:"Contraire de long, ou l'ordre lance au sprinteur.",
    MILLE:"Dix fois cent, borne ronde des grands nombres.",
    DANSE:"Le corps epouse la musique en mouvements.",
    CHANT:"Melodie sortie du gosier, du coq a l'aube ou de la diva.",
    RIRES:"Eclats joyeux, dit-on les meilleurs remedes.",
  },
  en: {
    APPLE:"One a day supposedly keeps the doctor at bay; it fell on a thinker's head.",
    HOUSE:"Four walls, a roof, and everyone's dream to own.",
    TABLE:"Four legs, never walks, holds your dinner.",
    CHAIR:"Take one to sit, or to lead the meeting.",
    WATER:"Two of one gas, one of another; life leans on it.",
    LIGHT:"Darkness flees before it; also the opposite of heavy.",
    NIGHT:"The sun clocks out and the stars clock in.",
    MONEY:"It talks, they say, but can't buy happiness.",
    HAPPY:"The dwarf who always grins; the mood of a fine day.",
    MUSIC:"It soothes the savage beast, woven of notes and beat.",
    DANCE:"Bodies obey the rhythm.",
    SMILE:"Flip a frown and this is what you get.",
    HEART:"A tireless drum in the chest; love's red shape.",
    BRAIN:"Grey matter that never stops plotting.",
    POWER:"It corrupts, they warn; also what a socket delivers.",
    SPACE:"The final frontier, black and endless.",
    EARTH:"Third rock from the sun.",
    OCEAN:"Salty giant where the whales roam.",
    RIVER:"It runs but never tires, always toward the sea.",
    BEACH:"Where land surrenders to the tide, grain by grain.",
    CLOUD:"A wanderer of the sky that sometimes weeps.",
    STORM:"First the flash, then the roar of an angry sky.",
    GREEN:"Envy's shade, and the light that says go.",
    WHITE:"All colors of light combined; the flag of surrender.",
    BLACK:"The color of mourning and a very strong coffee.",
    BROWN:"The shade of soil, bark and chocolate.",
    PLANT:"It drinks through roots and eats the sun.",
    TREES:"Silent giants that shed their coats in autumn, plural.",
    GRASS:"The green blades a mower dreads.",
    FRUIT:"The reward of a tree, and of honest labor.",
    LEMON:"So sour it puckers; also a car that keeps breaking down.",
    MANGO:"Tropical gold with a stubborn stone inside.",
    BREAD:"Slang for cash; the baker's daily miracle.",
    SUGAR:"Sweet crystal, sworn foe of the dentist.",
    HONEY:"A hive's golden gift, and a word for a sweetheart.",
    JUICE:"The very soul squeezed from an orange.",
    PIZZA:"A round pie sliced like a clock, born in Naples.",
    SALAD:"A green bowl the health-conscious adore.",
    STEAK:"The ogre wants it rare and dripping.",
    PASTA:"Italy's flour ropes, twirled on a fork.",
    CANDY:"A dentist's nightmare kids can't resist.",
    SWEET:"Sugar's flavor, or a term of endearment.",
    GRAPE:"It hangs in bunches and dreams of becoming wine.",
    PEACH:"Fuzzy skin, hard heart; also a flawless person.",
    BERRY:"Small and juicy, it grows on the bush.",
    MELON:"A heavy round fruit; slang for a head.",
    TIGER:"Striped fire of the jungle, burning bright.",
    LIONS:"Manes and roars, kings without a throne, plural.",
    BEARS:"They sleep through winter and crave honey, plural.",
    HORSE:"A unit of engine power bears its name; it neighs.",
    SHEEP:"Count them to fall asleep; wool on four legs.",
    GOATS:"They butt heads and eat almost anything, plural.",
    MOUSE:"A cat's endless chase, or the thing under your palm.",
    SNAKE:"No legs, all spine; it tempted Eve.",
    EAGLE:"A nation's emblem soaring on razor sight.",
    SHARK:"Rows of teeth cruising the deep; also a ruthless lender.",
    WHALE:"The sea's colossus, yet it feeds on the tiny.",
    ZEBRA:"A striped street crossing borrows its name.",
    PANDA:"A black-eyed bear addicted to bamboo.",
    KOALA:"It clings to a branch and sleeps all day.",
    CAMEL:"A desert ship with humps for a fuel tank.",
    PUPPY:"A dog still learning how to bark.",
    KITTY:"A tiny cat, or the pot of money in a game.",
    FROGS:"Green princes awaiting a kiss, plural.",
    DUCKS:"They waddle, swim and dodge, plural.",
    BIRDS:"Two in a bush beat one in the hand, plural.",
    SCORE:"The tally at the end; also twenty in old speak.",
    POINT:"A dot on the map, or what wins the game.",
    LEVEL:"Flat as a floor, or a stage in a game.",
    BOARD:"Step on one to sail, or set the chessmen on it.",
    CHESS:"A silent war of kings and pawns.",
    CARDS:"Hold them close and never show your hand, plural.",
    MATCH:"Two teams clash; also what lights a candle.",
    QUEEN:"She rules the hive and the chessboard alike.",
    KINGS:"Crowned men, or the three who followed a star, plural.",
    ROOKS:"Chess towers, or crafty black birds, plural.",
    PAWNS:"Front-line chess soldiers, sacrificed with ease, plural.",
    PIECE:"A slice of the whole, or a single chessman.",
    HELLO:"The first word of any phone call.",
    WORLD:"A stage, said the Bard; the whole of it.",
    SMART:"Clever, or a very tiny car brand.",
    QUICK:"Faster than a wink.",
    BRAVE:"Fear's conqueror; a heart brimming with courage.",
    FUNNY:"It tickles the ribs and cracks you up.",
    LUCKY:"Born under a good star; a rabbit's foot grants it.",
    MAGIC:"Abracadabra makes it happen.",
    DREAM:"A midnight movie the mind screens for free.",
    SLEEP:"Eight hours the body begs for each night.",
    LEARN:"You do it best from your mistakes, they say.",
    STUDY:"Cramming before the dreaded exam.",
    BOOKS:"Never judge them by their covers, plural.",
    WORDS:"Actions speak louder than these, plural.",
    VOWEL:"Sometimes Y, always A, E, I, O and U.",
    SOUND:"Sight for the ears; it needs air to travel.",
    VOICE:"Your personal instrument, no strings attached.",
    PHONE:"It rings, it scrolls, it rules your pocket.",
    VIDEO:"It killed the radio star, so the song goes.",
    EMAIL:"Post with no stamp, delivered at the speed of light.",
    ROBOT:"A tireless servant of gears and code.",
    TRAIN:"It hugs two rails and never strays off track.",
    PLANE:"Heavier than air, yet it defies gravity.",
    HOTEL:"A home with room service and a key to hand back.",
    GLASS:"See through it; half full for the optimist.",
    PLATE:"A round stage for your dinner; tectonic ones drift.",
    SPOON:"Born with a silver one means born to riches.",
    KNIFE:"It cuts both ways, so they warn.",
    CLOCK:"Its hands hold nothing, yet they rule the day.",
    WATCH:"A tiny timepiece on a wrist; also to keep an eye out.",
    SHOES:"If they fit, wear them, plural.",
    SHIRT:"You'd give it off your back for a friend.",
    PANTS:"Two legs of fabric; the boss allegedly wears them, plural.",
    DRESS:"A one-piece gown; also to put on your clothes.",
    SOCKS:"They vanish in the laundry, one of a pair, plural.",
    TOWEL:"Throw it in and you give up; otherwise it dries you.",
    BRUSH:"It tames your hair or coats a wall in color.",
    MOUNT:"A giant of rock; also to climb onto a steed.",
    FIELD:"Where crops grow or a match is fought.",
    GRAND:"A thousand bucks, or something majestic.",
    SUNNY:"The forecast everyone hopes to hear.",
    RAINY:"Save for such a day, the wise advise.",
    WINDY:"The kind of day a kite adores.",
    FROST:"Winter's white breath upon the grass.",
    SPARK:"A fire's first tiny hello; also a bright idea.",
    FLAME:"A candle's dancing tongue.",
    STONE:"Roll it and no moss grows; skip it on the pond.",
    METAL:"It rings when struck; gold and iron are kin.",
    PAPER:"It beats rock in a hand game; born from a tree.",
    WOODS:"You can't see the forest for these, plural.",
    CROWN:"Heavy lies the head that wears it.",
  },
};
